# Generated by Django 2.2 on 2021-08-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20210812_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
