# Generated by Django 2.2 on 2021-08-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_auto_20210812_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
